services:
  code:
    image: lscr.io/linuxserver/code-server:4.103.2
    container_name: code
    hostname: code
    env_file:
      - .env
    volumes:
      - ./src/common/custom-cont-init.d/master-install.sh:/custom-cont-init.d/master-install.sh           # master install
      - ./src/shell/install-scripts:/ysc/install-scripts/00_shell:ro                                      # installation scripts (shell)
      - ./src/ansible/install-scripts:/ysc/install-scripts/10_ansible:ro                                  # installation scripts (ansible)
      - ./src/agnide/install-scripts:/ysc/install-scripts/agnide:ro                                       # installation scripts (vscode)
      - ./src/shell/oh-my-zsh-config:/ysc/oh-my-zsh-config:ro                                             # user settings (shell)
      - ./src/agnide/vs-code:/ysc/vs-code:ro                                                              # user settings (vscode)
      - ~/.ssh/id_rsa:/config/.ssh/id_rsa:ro                                                              # client ssh private key
      - ~/.ssh/id_rsa.pub:/config/.ssh/id_rsa.pub:ro                                                      # client ssh public key
      - ${HOST_WORK_DIR}/shell.sshdata:/config/ssh_host_keys                                              # server ssh keys
      - ${HOST_WORK_DIR}/shell.codedata:/config/workspace                                                 # workspace
    restart: unless-stopped
