version: "3"
services:
  shell:
    networks:
      - pinanas_pinanas

  agnide:
    networks:
      - pinanas_pinanas
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.code-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.code-secure.entrypoints=https"
      - "traefik.http.routers.code-secure.middlewares=authelia@docker"
      - "traefik.http.routers.code-secure.rule=Host(`code.${HOME_DOMAIN}`)"
      - "traefik.http.routers.code-secure.service=code"
      - "traefik.http.routers.code-secure.tls=true"
      - "traefik.http.routers.code.entrypoints=http"
      - "traefik.http.routers.code.middlewares=code-https-redirect"
      - "traefik.http.routers.code.rule=Host(`code.${HOME_DOMAIN}`)"
      - "traefik.http.services.code.loadbalancer.server.port=8443"

networks:
  pinanas_pinanas:
    external: true
