version: "3"
services:
  shell:
    image: lscr.io/linuxserver/openssh-server:version-8.6_p1-r3
    container_name: yscialom_devenv_shell
    hostname: shell
    env_file:
      - .env
    environment:
      - PUBLIC_KEY_FILE=/config/.ssh/id_rsa.pub
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=false
      - VERSION=0.1.0
    volumes:
      - ./src/common/custom-cont-init.d/master-install.sh:/config/custom-cont-init.d/master-install.sh:ro # master install
      - ./src/shell/install-scripts:/ysc/install-scripts/00_shell:ro                                      # installation scripts
      - ./src/ansible/install-scripts:/ysc/install-scripts/10_ansible:ro                                  # installation scripts
      - ./src/shell/oh-my-zsh-config:/ysc/oh-my-zsh-config:ro                                             # user settings
      - ./src/shell/git-config:/ysc/git-config:ro                                                         # git settings
      - ~/.ssh/id_rsa:/config/.ssh/id_rsa:ro                                                              # client ssh private key
      - ~/.ssh/id_rsa.pub:/config/.ssh/id_rsa.pub:ro                                                      # client ssh public key
      - ${HOST_WORK_DIR}/shell.sshdata:/config/ssh_host_keys                                              # server ssh keys
      - ${HOST_WORK_DIR}/shell.codedata:/config/workspace                                                 # workspace
    restart: unless-stopped

  agnide:
    build:
      context: src
      dockerfile: agnide/Dockerfile
    container_name: yscialom_devenv_agnide
    hostname: agnide
    env_file:
      - .env
    volumes:
      - ./src/agnide/install-scripts:/ysc/install-scripts/agnide:ro                                       # installation scripts
      - ./src/agnide/vs-code:/ysc/vs-code:ro                                                              # user settings
      - ~/.ssh/id_rsa:/config/.ssh/id_rsa                                                                 # client ssh private key
      - ~/.ssh/id_rsa.pub:/config/.ssh/id_rsa.pub                                                         # client ssh public key
      - ${HOST_WORK_DIR}/shell.codedata:/config/workspace                                                 # workspace
    restart: unless-stopped
